### test pxg
GET http://localhost:7758/exchange/get_eth_account?account_name=tbgjoin

###check eth address
POST  http://localhost:7758/exchange/check_eth_account
content-type: application/json

{
    "transfer_from_address":"0xE543732c26f84A83E7FcE1fE9479376400344d5D",
    "transfer_amount":"500000"
}

### record_trx
POST http://localhost:7758/exchange/record_trx
content-type: application/json

{
    "pog_account":"TES2",
    "trx_id":"0x2926c4d3d6c876d41448fd35054685beee22f0d2a9882f682749e81376c33adb",
    "transfer_from_address":"0x0e1d7ed21ab2f48c7a97be6ff8c816ce221b2cb8",
    "transfer_to_address":"0xd73b2c72435276c98a1266db457fbcd0c2d2bf28",
    "transfer_amount":"0"
}
### get history
GET http://localhost:7758/exchange/history_exchange_records?pog_account=TES3


### get detail
GET http://localhost:7758/exchange/get_record_detail?record_id=Rets_vsn