### test pxg
GET http://localhost:7758/exchange/get_eth_account?account_name=tbgjoin

###check eth address
POST  http://localhost:7758/exchange/check_eth_account
content-type: application/json

{
    "transfer_from_address":"0xE543732c26f84A83E7FcE1fE9479376400344d5D",
    "transfer_amount":"500000"
}

### record_trx
POST http://localhost:7758/exchange/record_trx
content-type: application/json

{
    "pog_account":"11g22p33s",
    "trx_id":"0xb166c34245bad2b07a1a1d67f0eccb436c20c759e5e55e7b967e0bf34d878251",
    "transfer_from_address":"0x813f20301ccf5825e7a34936a12385c38989301d",
    "transfer_to_address":"0xbb123b7f59c2f85049be43bc612c92a04558f125",
    "transfer_amount":"10"
}
### get history
GET http://localhost:7758/exchange/history_exchange_records?pog_account=TES3


### get detail
GET http://localhost:7758/exchange/get_record_detail?record_id=Rets_vsn