// @ts-check


// 获取eth账号
const GET_ETH_ACC = "GET_ETH_ACC";


//消息队列常量-处理转账
const HANDLE_TRANSFER2POG = "HANDLE_TRANSFER2POG";
const HANDLE_TRANSFER2ETH = "HANDLE_TRANSFER2ETH";
const HANDLE_TRANSFER2CHARGE = "HANDLE_TRANSFER2CHARGE";
/**
 * 消息队列配置变量
 */
const CONSTANT = {
    "GET_ETH_ACC" : GET_ETH_ACC,
    "HANDLE_TRANSFER2POG"  : HANDLE_TRANSFER2POG,
    "HANDLE_TRANSFER2ETH":HANDLE_TRANSFER2ETH,
    "HANDLE_TRANSFER2CHARGE":HANDLE_TRANSFER2CHARGE

}

module.exports = CONSTANT
